# Simple workflow for deploying static content to GitHub Pages
name: Documentation Deployment

on:
  # Runs on pushes targeting the default branch
  workflow_run:
      workflows: ["Tests and Build Docs"]
      branches: ["main"]
      types:
          - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Set up Python
        # This is the version of the action for setting up Python, not the Python version.
        uses: actions/setup-python@v5
        with:
          # Semantic version range syntax or exact version of a Python version
          python-version: '3.12'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
          cache: 'pip'
      - name: Install Dependencies
        run: |
            pip install --upgrade pip
            pip install .[docs]
      - name: Build Docs
        run: |
          pushd docs
          make html
      - name: Upload artifact
        if: ${{ github.head_ref == 'main' || github.ref_name == 'main' }}
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'docs/_build/html'
      - name: Deploy to GitHub Pages
        if: ${{ github.head_ref == 'main' || github.ref_name == 'main' }}
        id: deployment
        uses: actions/deploy-pages@v4
